version: '3.8'
services:
  api:
    build: .
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - mongodb
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spotify_ai
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
